name: Build and Test

on:
  push:
    branches:
      - master # Personnalisez la branche si nécessaire

jobs:
  build:
    runs-on: windows-latest # Vous pouvez utiliser un autre système d'exploitation si nécessaire

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # Choisissez la version de Java que vous utilisez
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test
